# Generated by Django 5.2.12 on 2026-03-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usersecuritystate'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersecuritystate',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersecuritystate',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='usersecuritystate',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
