# Generated by Django 5.2.12 on 2026-03-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_document_job_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='template_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
